project:
  type: default
  render:
    - docs/index.qmd

execute:
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    embed-resources: true
    html-math-method: katex
    theme: cosmo
